/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package threejava.frame;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import threejava.game.GameStatus;
import threejava.listener.ThreeJavaMouseListener;

/**
 *
 * @author bloodyparadise
 */
public class MainFrame extends javax.swing.JFrame {
    private ThreeJavaMouseListener mouseListener;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initMyComponents();
        readHighScore();
        mouseListener = new ThreeJavaMouseListener(this);
        this.addMouseListener(mouseListener);
        this.addMouseMotionListener(mouseListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        nextBlockLabel = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        gameBoardBottom = new javax.swing.JPanel();
        nextBlockBottom = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        scorePanel = new javax.swing.JLabel();
        highscoreLabel = new javax.swing.JLabel();
        highscorePanel = new javax.swing.JLabel();
        aboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoLabel.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        logoLabel.setText("Three! in Java");

        nextBlockLabel.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        nextBlockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextBlockLabel.setText("Next Block");

        newGameButton.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameBoardBottomLayout = new javax.swing.GroupLayout(gameBoardBottom);
        gameBoardBottom.setLayout(gameBoardBottomLayout);
        gameBoardBottomLayout.setHorizontalGroup(
            gameBoardBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gameBoardBottomLayout.setVerticalGroup(
            gameBoardBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout nextBlockBottomLayout = new javax.swing.GroupLayout(nextBlockBottom);
        nextBlockBottom.setLayout(nextBlockBottomLayout);
        nextBlockBottomLayout.setHorizontalGroup(
            nextBlockBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        nextBlockBottomLayout.setVerticalGroup(
            nextBlockBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        scoreLabel.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("Score");

        scorePanel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        scorePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scorePanel.setText(" ");

        highscoreLabel.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        highscoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscoreLabel.setText("High Score");

        highscorePanel.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        highscorePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscorePanel.setText(" ");

        aboutButton.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newGameButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(exitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextBlockLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextBlockBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(highscoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(highscorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gameBoardBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 176, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton)
                        .addGap(39, 39, 39)
                        .addComponent(nextBlockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextBlockBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(highscoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(highscorePanel))
                    .addComponent(gameBoardBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMyComponents() {
        gameBoardBottom.setBorder(BorderFactory.createEtchedBorder());
        gameBoard = new GameBoardPanel();
        gameBoard.setVisible(true);
        gameBoardBottom.setLayout(new BorderLayout());
        gameBoardBottom.add(gameBoard,BorderLayout.CENTER);
        
        nextBlockBottom.setBorder(BorderFactory.createEtchedBorder());
        nextBlockPanel = new NextBlockPanel();
        nextBlockPanel.setVisible(true);
        nextBlockBottom.setLayout(new BorderLayout());
        nextBlockBottom.add(nextBlockPanel,BorderLayout.CENTER);
        pack();
    }
    
    private void readHighScore(){
        File highscore = new File("highscore");
        if(!highscore.exists()){
            OutputStream out;
            try {
                out = new FileOutputStream(highscore); //如果文件不存在会自动创建
                String str="0";
                byte[] b=str.getBytes();
                out.write(b);//因为是字节流，所以要转化成字节数组进行输出
                out.close();
                this.highscorePanel.setText("0");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            InputStream in;
            try {
                in = new FileInputStream(highscore);
                byte[] b=new byte[(int) highscore.length()];
                in.read(b);
                in.close();
                String s = new String(b);
                this.highscorePanel.setText(s);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        startGame();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        String about = "Original Game:https://itunes.apple.com/us/app/threes!/id779157948";
        String about2 = "Java version written by Xiaochen Zhu:zhuxiaochen.thu@gmail.com";
        JOptionPane.showMessageDialog(this,about+"\n"+about2);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void startGame() {
        status = new GameStatus();
        scorePanel.setText(" ");
        gameBoard.setStatus(status);
        gameBoard.repaint();
        nextBlockPanel.setStatus(status);
        nextBlockPanel.repaint();
    }
    
    public JLabel getNextBlockLabel(){
        return nextBlockLabel;
    }
    
    public GameBoardPanel getGameBoardPanel(){
        return gameBoard;
    }
    
    public JLabel getScorePanel(){
        return scorePanel;
    }
    
    public NextBlockPanel getNextBlockPanel(){
        return nextBlockPanel;
    }
    
    public JLabel getHighscorePanel(){
        return highscorePanel;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel gameBoardBottom;
    private javax.swing.JLabel highscoreLabel;
    private javax.swing.JLabel highscorePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton newGameButton;
    private javax.swing.JPanel nextBlockBottom;
    private javax.swing.JLabel nextBlockLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scorePanel;
    // End of variables declaration//GEN-END:variables
    private GameBoardPanel gameBoard;
    private NextBlockPanel nextBlockPanel;
    private GameStatus status;
    
    
}
